import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "../globals.css";
import Header from "./header";
import Footer from "./Footer";
import { ThemeProvider } from "../components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const billabong = localFont({
  src : '../../../public/fonts/Billabong.ttf',
  variable: '--font-billabong',
  weight: '400',
  display: 'swap',
})

const montserrat = localFont({
  src : '../../../public/fonts/Montserrat-Bold.ttf',
  variable: '--font-montserrat',
  weight: '400',
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${billabong.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className=" min-h-13">
            <Header />
          </div>
          {children}
          
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
